name: e2e Tests with Allure

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout test repo
        uses: actions/checkout@v3

      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: Zambom2021/temple-of-rock
          token: ${{ secrets.TEMPLE_TOKEN }}
          path: app

      - name: Start Backend
        run: |
          cd app
          docker compose up -d --build

          echo "Aguardando backend subir..."
          for i in {1..40}; do
            if curl -s http://localhost:9090/web/ >/dev/null; then
              echo "Backend OK"
              break
            fi
            echo "Iniciando... ($i)"
            sleep 3
          done

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Google Chrome + Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb

          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"

          echo "Chrome version: $CHROME_VERSION"
          wget -q $DRIVER_URL -O driver.zip
          unzip driver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

          chromedriver --version
          google-chrome --version

      - name: Install Dependencies
        run: mvn -B install -DskipTests

      - name: Run Tests
        run: HEADLESS=true mvn -B test

      # 🔥 Gera o relatório HTML (target/allure-report)
      - name: Generate Allure HTML Report
        if: always()
        run: mvn allure:report

      # 🔥 Envia apenas os arquivos corretos do Allure
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      # 🔥 Envia o relatório HTML completo
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Down Docker
        if: always()
        run: docker compose -f app/docker-compose.yml down -v
